In [118]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot
%matplotlib inline

# FIXME: Tweak learning rates, dropouts, batchnormalization, regularlization 

In [119]:
redwine_data = pd.read_csv(r'redwine_data.csv', sep=',', index_col=0)



In [120]:
redwine_data.head()

fixed.acidity  volatile.acidity  citric.acid  residual.sugar  chlorides  \
1            7.4              0.70         0.00             1.9      0.076   
2            7.8              0.88         0.00             2.6      0.098   
3            7.8              0.76         0.04             2.3      0.092   
4           11.2              0.28         0.56             1.9      0.075   
5            7.4              0.70         0.00             1.9      0.076   

   free.sulfur.dioxide  total.sulfur.dioxide  density    pH  sulphates  \
1                 11.0                  34.0   0.9978  3.51       0.56   
2                 25.0                  67.0   0.9968  3.20       0.68   
3                 15.0                  54.0   0.9970  3.26       0.65   
4                 17.0                  60.0   0.9980  3.16       0.58   
5                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
1      9.4        5  
2      9.8        5  
3      9.8        5  
4      9.8        6  
5      9.4        5

In [121]:
# Data proprocessing
features = redwine_data.iloc[:,0:11].values
labels = redwine_data.iloc[:,11].values


In [122]:
print(features)

[[ 7.4    0.7    0.    ...  3.51   0.56   9.4  ]
 [ 7.8    0.88   0.    ...  3.2    0.68   9.8  ]
 [ 7.8    0.76   0.04  ...  3.26   0.65   9.8  ]
 ...
 [ 6.3    0.51   0.13  ...  3.42   0.75  11.   ]
 [ 5.9    0.645  0.12  ...  3.57   0.71  10.2  ]
 [ 6.     0.31   0.47  ...  3.39   0.66  11.   ]]


In [123]:
# convert labe array to one hot encoded matrix

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(labels)
labels = pd.get_dummies(y).values


In [124]:
# split data into training and test sets

from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.2, random_state = 0)

In [125]:
#scaling the data
from sklearn.preprocessing import StandardScaler
feature_scaler = StandardScaler()
train_features = feature_scaler.fit_transform(train_features)
test_features = feature_scaler.transform(test_features)


In [126]:
import keras
from keras.models import Sequential
from keras.layers import Dense


In [127]:
# Initialize the network
ann_clf = Sequential()

In [128]:
# adding input and hidden layers

#TODO: Try better initializer. e.g
#keras.initializers.he_normal(seed=None)

# hidden layer
# units = average of input and output nodes, (11 input nodes + 6 output nodes) / 2  = 8.5
# relu = rectifier function
h1 = Dense(units = 9, kernel_initializer='he_normal', activation='relu', input_dim=11)
ann_clf.add(h1)

# second hidden layer
h2 = Dense(units = 9, kernel_initializer = 'he_normal', activation='relu')
ann_clf.add(h2)


In [129]:
# output layers
op = Dense(units=6, kernel_initializer = 'he_normal', activation='softmax')
ann_clf.add(op)

In [130]:
# Training the neural network

# Configure the right optimizer and loss functions
ann_clf.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



In [131]:
# Start training
ann_clf.fit(train_features, train_labels, batch_size=1, epochs=500)


Epoch 1/500
1279/1279 [==============================] - 1s 945us/step - loss: 1.3443 - acc: 0.4762
Epoch 2/500
1279/1279 [==============================] - 1s 697us/step - loss: 1.0853 - acc: 0.5309
Epoch 3/500
1279/1279 [==============================] - 1s 706us/step - loss: 1.0308 - acc: 0.5575
Epoch 4/500
1279/1279 [==============================] - 1s 706us/step - loss: 1.0014 - acc: 0.5778
Epoch 5/500
1279/1279 [==============================] - 1s 733us/step - loss: 0.9818 - acc: 0.5927
Epoch 6/500
1279/1279 [==============================] - 1s 714us/step - loss: 0.9650 - acc: 0.6020
Epoch 7/500
1279/1279 [==============================] - 1s 714us/step - loss: 0.9526 - acc: 0.5950
Epoch 8/500
1279/1279 [==============================] - 1s 681us/step - loss: 0.9432 - acc: 0.6005
Epoch 9/500
1279/1279 [==============================] - 1s 629us/step - loss: 0.9298 - acc: 0.6169
Epoch 10/500
1279/1279 [==============================] - 1s 704us/step - loss: 0.9237 - acc: 0.6224

1279/1279 [==============================] - 1s 775us/step - loss: 0.7724 - acc: 0.6818
Epoch 82/500
1279/1279 [==============================] - 1s 803us/step - loss: 0.7756 - acc: 0.6716
Epoch 83/500
1279/1279 [==============================] - 1s 806us/step - loss: 0.7696 - acc: 0.6724
Epoch 84/500
1279/1279 [==============================] - 1s 813us/step - loss: 0.7702 - acc: 0.6771
Epoch 85/500
1279/1279 [==============================] - 1s 760us/step - loss: 0.7718 - acc: 0.6740
Epoch 86/500
1279/1279 [==============================] - 1s 781us/step - loss: 0.7682 - acc: 0.6794
Epoch 87/500
1279/1279 [==============================] - 1s 793us/step - loss: 0.7684 - acc: 0.6810
Epoch 88/500
1279/1279 [==============================] - 1s 755us/step - loss: 0.7713 - acc: 0.6677
Epoch 89/500
1279/1279 [==============================] - 1s 736us/step - loss: 0.7683 - acc: 0.6787
Epoch 90/500
1279/1279 [==============================] - 1s 790us/step - loss: 0.7643 - acc: 0.6810
Epo

1279/1279 [==============================] - 1s 710us/step - loss: 0.7476 - acc: 0.6865
Epoch 161/500
1279/1279 [==============================] - 1s 677us/step - loss: 0.7450 - acc: 0.6927
Epoch 162/500
1279/1279 [==============================] - 1s 728us/step - loss: 0.7459 - acc: 0.6826
Epoch 163/500
1279/1279 [==============================] - 1s 719us/step - loss: 0.7481 - acc: 0.6912
Epoch 164/500
1279/1279 [==============================] - 1s 728us/step - loss: 0.7402 - acc: 0.6904
Epoch 165/500
1279/1279 [==============================] - 1s 658us/step - loss: 0.7420 - acc: 0.6959
Epoch 166/500
1279/1279 [==============================] - 1s 643us/step - loss: 0.7435 - acc: 0.6998
Epoch 167/500
1279/1279 [==============================] - 1s 645us/step - loss: 0.7446 - acc: 0.6857
Epoch 168/500
1279/1279 [==============================] - 1s 636us/step - loss: 0.7420 - acc: 0.6919
Epoch 169/500
1279/1279 [==============================] - 1s 655us/step - loss: 0.7396 - acc: 0

1279/1279 [==============================] - 1s 655us/step - loss: 0.7271 - acc: 0.6943
Epoch 240/500
1279/1279 [==============================] - 1s 658us/step - loss: 0.7237 - acc: 0.7005
Epoch 241/500
1279/1279 [==============================] - 1s 691us/step - loss: 0.7226 - acc: 0.7052
Epoch 242/500
1279/1279 [==============================] - 1s 751us/step - loss: 0.7240 - acc: 0.6974
Epoch 243/500
1279/1279 [==============================] - 1s 584us/step - loss: 0.7233 - acc: 0.6982
Epoch 244/500
1279/1279 [==============================] - 1s 555us/step - loss: 0.7245 - acc: 0.7021
Epoch 245/500
1279/1279 [==============================] - 1s 555us/step - loss: 0.7246 - acc: 0.7029
Epoch 246/500
1279/1279 [==============================] - 1s 549us/step - loss: 0.7272 - acc: 0.6951
Epoch 247/500
1279/1279 [==============================] - 1s 548us/step - loss: 0.7209 - acc: 0.7076
Epoch 248/500
1279/1279 [==============================] - 1s 546us/step - loss: 0.7260 - acc: 0

1279/1279 [==============================] - 1s 772us/step - loss: 0.7116 - acc: 0.7052
Epoch 319/500
1279/1279 [==============================] - 1s 766us/step - loss: 0.7094 - acc: 0.7146
Epoch 320/500
1279/1279 [==============================] - 1s 741us/step - loss: 0.7173 - acc: 0.7052
Epoch 321/500
1279/1279 [==============================] - 1s 769us/step - loss: 0.7147 - acc: 0.7045
Epoch 322/500
1279/1279 [==============================] - 1s 712us/step - loss: 0.7141 - acc: 0.7076
Epoch 323/500
1279/1279 [==============================] - 1s 741us/step - loss: 0.7136 - acc: 0.7115
Epoch 324/500
1279/1279 [==============================] - 1s 747us/step - loss: 0.7175 - acc: 0.7021
Epoch 325/500
1279/1279 [==============================] - 1s 727us/step - loss: 0.7160 - acc: 0.7045
Epoch 326/500
1279/1279 [==============================] - 1s 774us/step - loss: 0.7170 - acc: 0.6990
Epoch 327/500
1279/1279 [==============================] - 1s 699us/step - loss: 0.7123 - acc: 0

1279/1279 [==============================] - 1s 784us/step - loss: 0.7082 - acc: 0.7154
Epoch 397/500
1279/1279 [==============================] - 1s 807us/step - loss: 0.7129 - acc: 0.7107
Epoch 398/500
1279/1279 [==============================] - 1s 856us/step - loss: 0.7137 - acc: 0.7021
Epoch 399/500
1279/1279 [==============================] - 1s 842us/step - loss: 0.7144 - acc: 0.7052
Epoch 400/500
1279/1279 [==============================] - 1s 737us/step - loss: 0.7098 - acc: 0.7091
Epoch 401/500
1279/1279 [==============================] - 1s 824us/step - loss: 0.7078 - acc: 0.7076
Epoch 402/500
1279/1279 [==============================] - 1s 857us/step - loss: 0.7181 - acc: 0.6998
Epoch 403/500
1279/1279 [==============================] - 1s 786us/step - loss: 0.7146 - acc: 0.7013
Epoch 404/500
1279/1279 [==============================] - 1s 886us/step - loss: 0.7039 - acc: 0.7146
Epoch 405/500
1279/1279 [==============================] - 1s 826us/step - loss: 0.7097 - acc: 0

1279/1279 [==============================] - 1s 667us/step - loss: 0.7037 - acc: 0.7091
Epoch 476/500
1279/1279 [==============================] - 1s 772us/step - loss: 0.7124 - acc: 0.7146
Epoch 477/500
1279/1279 [==============================] - 1s 763us/step - loss: 0.7098 - acc: 0.7123
Epoch 478/500
1279/1279 [==============================] - 1s 782us/step - loss: 0.7131 - acc: 0.6998
Epoch 479/500
1279/1279 [==============================] - 1s 765us/step - loss: 0.7145 - acc: 0.7076 0s - loss: 0.7188 - acc
Epoch 480/500
1279/1279 [==============================] - 1s 733us/step - loss: 0.7087 - acc: 0.7107
Epoch 481/500
1279/1279 [==============================] - 1s 735us/step - loss: 0.7101 - acc: 0.7115
Epoch 482/500
1279/1279 [==============================] - 1s 731us/step - loss: 0.7051 - acc: 0.7131
Epoch 483/500
1279/1279 [==============================] - 1s 721us/step - loss: 0.7092 - acc: 0.7115
Epoch 484/500
1279/1279 [==============================] - 1s 738us/step

In [132]:
predictions=ann_clf.predict(test_features)
predictions=np.argmax(predictions, axis=1)
test_labels=np.argmax(test_labels,axis=1)

In [133]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(test_labels,predictions))
print(classification_report(test_labels, predictions))
print(accuracy_score(test_labels, predictions))

[[ 0  0  2  0  0  0]
 [ 0  0  8  3  0  0]
 [ 1  1 93 39  1  0]
 [ 0  1 37 88 15  1]
 [ 0  0  1 14 12  0]
 [ 0  0  0  1  2  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00        11
           2       0.66      0.69      0.67       135
           3       0.61      0.62      0.61       142
           4       0.40      0.44      0.42        27
           5       0.00      0.00      0.00         3

   micro avg       0.60      0.60      0.60       320
   macro avg       0.28      0.29      0.28       320
weighted avg       0.58      0.60      0.59       320

0.603125
