In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plot
%matplotlib inline


In [62]:
redwine_data = pd.read_csv(r'redwine_data.csv', sep=',', index_col=0)



In [63]:
redwine_data.head()

fixed.acidity  volatile.acidity  citric.acid  residual.sugar  chlorides  \
1            7.4              0.70         0.00             1.9      0.076   
2            7.8              0.88         0.00             2.6      0.098   
3            7.8              0.76         0.04             2.3      0.092   
4           11.2              0.28         0.56             1.9      0.075   
5            7.4              0.70         0.00             1.9      0.076   

   free.sulfur.dioxide  total.sulfur.dioxide  density    pH  sulphates  \
1                 11.0                  34.0   0.9978  3.51       0.56   
2                 25.0                  67.0   0.9968  3.20       0.68   
3                 15.0                  54.0   0.9970  3.26       0.65   
4                 17.0                  60.0   0.9980  3.16       0.58   
5                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
1      9.4        5  
2      9.8        5  
3      9.8        5  
4      9.8        6  
5      9.4        5

In [64]:
# Data proprocessing
features = redwine_data.iloc[:,0:11].values
labels = redwine_data.iloc[:,11].values


In [65]:
print(features)

[[ 7.4    0.7    0.    ...  3.51   0.56   9.4  ]
 [ 7.8    0.88   0.    ...  3.2    0.68   9.8  ]
 [ 7.8    0.76   0.04  ...  3.26   0.65   9.8  ]
 ...
 [ 6.3    0.51   0.13  ...  3.42   0.75  11.   ]
 [ 5.9    0.645  0.12  ...  3.57   0.71  10.2  ]
 [ 6.     0.31   0.47  ...  3.39   0.66  11.   ]]


In [66]:
# convert labe array to one hot encoded matrix

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(labels)
labels = pd.get_dummies(y).values


In [67]:
# split data into training and test sets

from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.2, random_state = 0)

In [68]:
#scaling the data
from sklearn.preprocessing import StandardScaler
feature_scaler = StandardScaler()
train_features = feature_scaler.fit_transform(train_features)
test_features = feature_scaler.transform(test_features)


In [69]:
import keras
from keras.models import Sequential
from keras.layers import Dense


In [70]:
# Initialize the network
ann_clf = Sequential()

In [71]:
# adding input and hidden layers

# hidden layer
# units = average of input and output nodes, (11 input nodes + 6 output nodes) / 2  = 8.5
# relu = rectifier function
h1 = Dense(units = 9, kernel_initializer='uniform', activation='relu', input_dim=11)
ann_clf.add(h1)

# second hidden layer
h2 = Dense(units = 9, kernel_initializer = 'uniform', activation='relu')
ann_clf.add(h2)

In [72]:
# output layers
op = Dense(units=6, kernel_initializer='uniform', activation='softmax')
ann_clf.add(op)

In [73]:
# Training the neural network

ann_clf.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



In [74]:
# Start training!!!!
ann_clf.fit(train_features, train_labels, batch_size=1, epochs=500)


W0622 09:03:29.822649 14036 deprecation.py:323] From C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0622 09:03:29.866553 14036 deprecation_wrapper.py:119] From C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/500
1279/1279 [==============================] - 1s 932us/step - loss: 1.2489 - acc: 0.4332
Epoch 2/500
1279/1279 [==============================] - 1s 721us/step - loss: 1.1055 - acc: 0.5192
Epoch 3/500
1279/1279 [==============================] - 1s 729us/step - loss: 1.0683 - acc: 0.5536
Epoch 4/500
1279/1279 [==============================] - 1s 726us/step - loss: 1.0176 - acc: 0.5575
Epoch 5/500
1279/1279 [==============================] - 1s 748us/step - loss: 0.9811 - acc: 0.5715
Epoch 6/500
1279/1279 [==============================] - 1s 807us/step - loss: 0.9592 - acc: 0.5833
Epoch 7/500
1279/1279 [==============================] - 1s 703us/step - loss: 0.9499 - acc: 0.5887
Epoch 8/500
1279/1279 [==============================] - 1s 636us/step - loss: 0.9399 - acc: 0.6052
Epoch 9/500
1279/1279 [==============================] - 1s 622us/step - loss: 0.9342 - acc: 0.5981
Epoch 10/500
1279/1279 [==============================] - 1s 630us/step - loss: 0.9323 - acc: 0.5880

1279/1279 [==============================] - 1s 591us/step - loss: 0.8550 - acc: 0.6224
Epoch 82/500
1279/1279 [==============================] - 1s 581us/step - loss: 0.8548 - acc: 0.6216
Epoch 83/500
1279/1279 [==============================] - 1s 594us/step - loss: 0.8574 - acc: 0.6263
Epoch 84/500
1279/1279 [==============================] - 1s 579us/step - loss: 0.8541 - acc: 0.6239
Epoch 85/500
1279/1279 [==============================] - 1s 579us/step - loss: 0.8525 - acc: 0.6200
Epoch 86/500
1279/1279 [==============================] - 1s 584us/step - loss: 0.8495 - acc: 0.6216
Epoch 87/500
1279/1279 [==============================] - 1s 585us/step - loss: 0.8518 - acc: 0.6247
Epoch 88/500
1279/1279 [==============================] - 1s 591us/step - loss: 0.8527 - acc: 0.6302
Epoch 89/500
1279/1279 [==============================] - 1s 579us/step - loss: 0.8505 - acc: 0.6231
Epoch 90/500
1279/1279 [==============================] - 1s 584us/step - loss: 0.8517 - acc: 0.6357
Epo

1279/1279 [==============================] - 1s 664us/step - loss: 0.8076 - acc: 0.6403
Epoch 161/500
1279/1279 [==============================] - 1s 710us/step - loss: 0.8019 - acc: 0.6497
Epoch 162/500
1279/1279 [==============================] - 1s 677us/step - loss: 0.8011 - acc: 0.6482
Epoch 163/500
1279/1279 [==============================] - 1s 640us/step - loss: 0.8055 - acc: 0.6396
Epoch 164/500
1279/1279 [==============================] - ETA: 0s - loss: 0.8076 - acc: 0.650 - 1s 637us/step - loss: 0.8048 - acc: 0.6513
Epoch 165/500
1279/1279 [==============================] - 1s 689us/step - loss: 0.8011 - acc: 0.6521
Epoch 166/500
1279/1279 [==============================] - 1s 694us/step - loss: 0.8005 - acc: 0.6560
Epoch 167/500
1279/1279 [==============================] - 1s 690us/step - loss: 0.8068 - acc: 0.6521
Epoch 168/500
1279/1279 [==============================] - 1s 655us/step - loss: 0.8052 - acc: 0.6482
Epoch 169/500
1279/1279 [==============================] -

1279/1279 [==============================] - 1s 681us/step - loss: 0.7874 - acc: 0.6615
Epoch 240/500
1279/1279 [==============================] - 1s 713us/step - loss: 0.7833 - acc: 0.6622
Epoch 241/500
1279/1279 [==============================] - 1s 673us/step - loss: 0.7890 - acc: 0.6482
Epoch 242/500
1279/1279 [==============================] - 1s 707us/step - loss: 0.7806 - acc: 0.6685
Epoch 243/500
1279/1279 [==============================] - 1s 719us/step - loss: 0.7823 - acc: 0.6630
Epoch 244/500
1279/1279 [==============================] - 1s 713us/step - loss: 0.7847 - acc: 0.6544
Epoch 245/500
1279/1279 [==============================] - 1s 740us/step - loss: 0.7866 - acc: 0.6615 0s - loss: 0.7788 - acc: 0.
Epoch 246/500
1279/1279 [==============================] - 1s 739us/step - loss: 0.7863 - acc: 0.6529
Epoch 247/500
1279/1279 [==============================] - 1s 733us/step - loss: 0.7827 - acc: 0.6505
Epoch 248/500
1279/1279 [==============================] - 1s 736us/

1279/1279 [==============================] - 1s 627us/step - loss: 0.7719 - acc: 0.6630
Epoch 318/500
1279/1279 [==============================] - 1s 620us/step - loss: 0.7718 - acc: 0.6677
Epoch 319/500
1279/1279 [==============================] - 1s 627us/step - loss: 0.7706 - acc: 0.6638
Epoch 320/500
1279/1279 [==============================] - 1s 621us/step - loss: 0.7749 - acc: 0.6646
Epoch 321/500
1279/1279 [==============================] - 1s 622us/step - loss: 0.7713 - acc: 0.6708
Epoch 322/500
1279/1279 [==============================] - 1s 605us/step - loss: 0.7731 - acc: 0.6622
Epoch 323/500
1279/1279 [==============================] - 1s 634us/step - loss: 0.7718 - acc: 0.6693
Epoch 324/500
1279/1279 [==============================] - 1s 673us/step - loss: 0.7699 - acc: 0.6638
Epoch 325/500
1279/1279 [==============================] - 1s 651us/step - loss: 0.7752 - acc: 0.6638
Epoch 326/500
1279/1279 [==============================] - 1s 631us/step - loss: 0.7689 - acc: 0

1279/1279 [==============================] - 1s 734us/step - loss: 0.7658 - acc: 0.6724
Epoch 397/500
1279/1279 [==============================] - 1s 825us/step - loss: 0.7652 - acc: 0.6740
Epoch 398/500
1279/1279 [==============================] - 1s 581us/step - loss: 0.7632 - acc: 0.6802
Epoch 399/500
1279/1279 [==============================] - 1s 597us/step - loss: 0.7635 - acc: 0.6693
Epoch 400/500
1279/1279 [==============================] - 1s 628us/step - loss: 0.7634 - acc: 0.6575
Epoch 401/500
1279/1279 [==============================] - 1s 569us/step - loss: 0.7647 - acc: 0.6708
Epoch 402/500
1279/1279 [==============================] - 1s 592us/step - loss: 0.7672 - acc: 0.6685
Epoch 403/500
1279/1279 [==============================] - 1s 543us/step - loss: 0.7630 - acc: 0.6740
Epoch 404/500
1279/1279 [==============================] - 1s 530us/step - loss: 0.7609 - acc: 0.6732
Epoch 405/500
1279/1279 [==============================] - 1s 580us/step - loss: 0.7698 - acc: 0

1279/1279 [==============================] - 1s 575us/step - loss: 0.7581 - acc: 0.6716
Epoch 474/500
1279/1279 [==============================] - 1s 537us/step - loss: 0.7653 - acc: 0.6787
Epoch 475/500
1279/1279 [==============================] - 1s 551us/step - loss: 0.7582 - acc: 0.6810
Epoch 476/500
1279/1279 [==============================] - 1s 557us/step - loss: 0.7593 - acc: 0.6779
Epoch 477/500
1279/1279 [==============================] - 1s 692us/step - loss: 0.7693 - acc: 0.6779
Epoch 478/500
1279/1279 [==============================] - 1s 639us/step - loss: 0.7579 - acc: 0.6787
Epoch 479/500
1279/1279 [==============================] - 1s 600us/step - loss: 0.7569 - acc: 0.6779
Epoch 480/500
1279/1279 [==============================] - 1s 593us/step - loss: 0.7571 - acc: 0.6833
Epoch 481/500
1279/1279 [==============================] - 1s 636us/step - loss: 0.7619 - acc: 0.6826 0s - loss: 0.654
Epoch 482/500
1279/1279 [==============================] - 1s 660us/step - loss

In [76]:
predictions=ann_clf.predict(test_features)
predictions=np.argmax(predictions, axis=1)
test_labels=np.argmax(test_labels,axis=1)

In [77]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(test_labels,predictions))
print(classification_report(test_labels, predictions))
print(accuracy_score(test_labels, predictions))

[[  0   0   1   1   0   0]
 [  0   0   4   7   0   0]
 [  0   2  74  59   0   0]
 [  0   0  23 101  17   1]
 [  0   0   1  15  11   0]
 [  0   0   0   1   2   0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00        11
           2       0.72      0.55      0.62       135
           3       0.55      0.71      0.62       142
           4       0.37      0.41      0.39        27
           5       0.00      0.00      0.00         3

   micro avg       0.58      0.58      0.58       320
   macro avg       0.27      0.28      0.27       320
weighted avg       0.58      0.58      0.57       320

0.58125


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
